// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXcneCoxs2Ar79fzLGA-et11xOeO7iPI',
    appId: '1:665876796564:web:6da1f95abef16083329081',
    messagingSenderId: '665876796564',
    projectId: 'budget-fb40b',
    authDomain: 'budget-fb40b.firebaseapp.com',
    databaseURL: 'https://budget-fb40b-default-rtdb.firebaseio.com',
    storageBucket: 'budget-fb40b.appspot.com',
    measurementId: 'G-Y3HYVZQ6YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA2-pdFNsH32ESLTDEfFNKrj5ckBLqNUQ',
    appId: '1:665876796564:android:72634d228a870958329081',
    messagingSenderId: '665876796564',
    projectId: 'budget-fb40b',
    databaseURL: 'https://budget-fb40b-default-rtdb.firebaseio.com',
    storageBucket: 'budget-fb40b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUaGwEAWyI4QFJdAy5ElQcoyhxyi4H_0',
    appId: '1:665876796564:ios:306aa9f796d3fe17329081',
    messagingSenderId: '665876796564',
    projectId: 'budget-fb40b',
    databaseURL: 'https://budget-fb40b-default-rtdb.firebaseio.com',
    storageBucket: 'budget-fb40b.appspot.com',
    iosClientId: '665876796564-rr08nsqec24bgi057q7p5f9ucnng8130.apps.googleusercontent.com',
    iosBundleId: 'com.example.bb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUaGwEAWyI4QFJdAy5ElQcoyhxyi4H_0',
    appId: '1:665876796564:ios:306aa9f796d3fe17329081',
    messagingSenderId: '665876796564',
    projectId: 'budget-fb40b',
    databaseURL: 'https://budget-fb40b-default-rtdb.firebaseio.com',
    storageBucket: 'budget-fb40b.appspot.com',
    iosClientId: '665876796564-rr08nsqec24bgi057q7p5f9ucnng8130.apps.googleusercontent.com',
    iosBundleId: 'com.example.bb',
  );
}
